### PR TITLE
CORE-1416: switch to a newer version of Go

### PR DESCRIPTION
**Pull request by slr71**
Note: most of this code is generated. The code that isn't generated is in `restapi/configure_permissions.go` and underneath `restapi/impl`. Most of the changes that were made to the Go source files were made to accommodate changes in the code that was generated by `go-swagger`. The rest of the Go source changes were made to fix lint warnings.

### CODE REVIEW

**Comment by slr71** [comment]
I updated the PR check to simply run `golint`. There are some warnings that I'm going to fix in an upcoming commit.

**Comment by slr71** [comment]
This PR is ready for review now.

**Review by ianmcorvidae — APPROVED** [review]
Looking at the namespaces you mention, seems reasonable to me. Hopefully I didn't go too crosseyed from all the added `*` and `&` and capitalization changes and missed something, but honestly if it compiles it probably works, given how Go works and the nature of these changes. So I say :shipit: !

**Comment by slr71** [comment]
Thanks for the review! The endpoints that I tested are working fine, although I admittedly didn't test all of them.

**Pull request merged**
